---
title: "function.Rmd"
author: "Sudesh Srivastav"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(roxygen2)
library(assertthat)
```

airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9


## Define conversion functions

First, F to C

```{r}

#' convert  degrees Fahrnheit to celsius
#'
#' we use the simple formula for temperature to convert
#' @parm fahr tmperature to converted in derees Fahrenheit
#'@return the temperature converted to degree celsius
#' @keywards temp conversion
#' @examples
#' fahr_to_celsius(32)
#' fahr_to_celsius(212, 100, 32))

fahr_to_celsius <- function(fahr) {
  #stopifnot(is.numeric(fahr))
  assert_that(is.numeric(fahr))
  celsius <- (fahr-32)*5/9
  return(celsius)
}
```


```{r}
celsius5<- fahr_to_celsius(airtemps[1])
celsius5 == celsius1

celsius <- fahr_to_celsius(airtemps)
celsius
```
```{r}
celsius_to_fahr <- function(cels) {
  fahr<-celsius*9/5 +32 
  return(fahr)
}
```
```{r}
airtemp2<-c(100.0000000,-0.9444444,  25.5555556,  0.0000000)
fahr <- celsius_to_fahr(airtemp2)
fahr == airtemps
```

